# Generated by Django 5.0.4 on 2024-04-16 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("exercises_info", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Routine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("like_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_routines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_users",
                    models.ManyToManyField(
                        related_name="liked_routines", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MirroredRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author_name", models.CharField(max_length=50)),
                (
                    "original_routine",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mirrored_routine",
                        to="my_health_info.routine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseInRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_in_routine",
                        to="exercises_info.exercisesinfo",
                    ),
                ),
                (
                    "mirrored_routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_in_routine",
                        to="my_health_info.mirroredroutine",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises_in_routine",
                        to="my_health_info.routine",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("mirrored_routine", "order"),
                    ("routine", "order"),
                },
            },
        ),
        migrations.CreateModel(
            name="UsersRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_author", models.BooleanField(default=False)),
                ("need_update", models.BooleanField(default=False)),
                (
                    "mirrored_routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mirrored_subscribers",
                        to="my_health_info.mirroredroutine",
                    ),
                ),
                (
                    "routine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscribers",
                        to="my_health_info.routine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "mirrored_routine"), ("user", "routine")},
            },
        ),
        migrations.CreateModel(
            name="ExerciseInRoutineAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_count", models.IntegerField(blank=True, default=0)),
                ("rep_count", models.PositiveIntegerField(blank=True, default=0)),
                ("weight", models.FloatField(blank=True, default=0)),
                ("duration", models.PositiveIntegerField(blank=True, default=0)),
                ("speed", models.FloatField(blank=True, default=0)),
                (
                    "exercise_in_routine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_attribute",
                        to="my_health_info.exerciseinroutine",
                    ),
                ),
            ],
            options={
                "unique_together": {("exercise_in_routine",)},
            },
        ),
        migrations.CreateModel(
            name="HealthInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="RoutineStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "mirrored_routine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="my_health_info.mirroredroutine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyRoutine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_index", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "users_routine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_health_info.usersroutine",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "day_index")},
            },
        ),
    ]
